### ISSUE TITLE
jupyter-themer not available on pip

### ISSUE THREAD

**Issue by hargup** [transcranial/jupyter-themer#1]
README says that `jupyter-themer` can be installed using `pip` by:

```
pip install jupyter-themer
```
but this give the following error, both on python 3 and python 2:
```
Could not find a version that satisfies the requirement jupyter-themer (from versions: )
No matching distribution found for jupyter-themer
```

Searching the package on PyPI [#1] also gives no result.

[#1]: https://pypi.python.org/pypi?%3Aaction=search&term=jupyter-themer&submit=search

**Comment by transcranial** [comment]
Apologies, should be all good as of yesterday. Incidentally, I've had SSL issues with pip on Mac OSX recently, but upgrading openssl resolved it.

**Comment by hargup** [comment]
Thanks! it works now.
