### ISSUE TITLE
Full Example Request

### ISSUE THREAD

**Issue by barnettjacob** [transcranial/jupyter-themer#3]
Hey. This looks really good and I'm really interesting in using but it isn't clear to me how to use the thing.

Can you include a simple worked example the readme? Thanks in advance.

Jacob

**Comment by mcolic** [comment]
Yes, I have the same issue. I am following everything, have my css files but can't make it work with my notebooks, can't apply it on them.

**Comment by transcranial** [comment]
@mcolic Did you remove your old ipython profiles? I'm still trying to figure out how to get jupyter to ignore them if they already exist. What's your platform and browser?

@barnettjacob https://github.com/transcranial/jupyter-themer#usage Once you install it, the command will be available in the command line. For example: `jupyter-themer -c base16-light -l wide -t serif`

**Comment by mcolic** [comment]
So I should remove all python profiles and then work on this one?

**Comment by mcolic** [comment]
My browser is safari and platform is python 3

**Comment by transcranial** [comment]
@mcolic Yeah, if you upgraded from ipython to jupyter, your old ipython profiles are probably still present (for example, at `~/.ipython`). Jupyter does away with separate profiles, and uses a single config. However, I think it still tries to use old ipython CSS files if they exist.

**Comment by milesgranger** [comment]
Hey, thanks for making this! You are right, about the ipython profiles as well. For others, if you simply rename your 'default_profile' folder to say 'ignore_default_profile' then this will work. Start the notebook, then in a seperate command line run "jupyter themer -c cobalt" for example. I'm not sure why people are confused about how to use this, as your instructions were quite clear. 

Thanks again!

**Comment by barnettjacob** [comment]
Thanks for following up, I got this working. Your `usage` section in the readme probably isn't explicit enough for those of us without a bunch of command line experience!
